name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Login to dockerhub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5 
      with:
       context: 
       push: true
       tags: nicolashmp/tp-yaml:latest
