name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      #uses: docker/build-push-action@v5
      run : |
        docker buildx create --use 
        docker buildx build --platform windows/adm64 -t nicolashmp/tp-yaml:latest

    - name: Clean up Docker
      run : docker system prune -af 
     # with:
      # context: 
      # push: true
      # tags: nicolashmp/tp-yaml:latest
