# Mod
name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: windows-latest

    env: 
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to dockerhub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker version
        docker buildx build --platform windows/amd64 -t nicolashmp/tp-yaml:latest . --push
    #- name: Build and push to dockerhub
    #  uses: docker/build-push-action@v5 
    #  with:
    #   context: 
    #   push: true
    #   tags: nicolashmp/tp-yaml:latest
